### ISSUE TITLE
Problem when I tried to install on ubuntu: latest

### ISSUE THREAD

**Issue by daiwang369** [coin-or/CyLP#100]
I tried "pip install cylp==0.9.4" with python3.7.8 on ubuntu, however, i got the following error. I do have pkg-config installed.

--------------------
 running build_ext
    building 'cylp.cy.CyClpPrimalColumnPivotBase' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/cylp
    creating build/temp.linux-x86_64-3.7/cylp/cpp
    creating build/temp.linux-x86_64-3.7/cylp/cy
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/travis/build/coin-or/build/include/coin -I./cylp/cpp -I./cylp/cy -I/usr/local/lib/python3.7/site-packages/numpy/core/include -I. -I/usr/local/include/python3.7m -c cylp/cpp/IClpPrimalColumnPivotBase.cpp -o build/temp.linux-x86_64-3.7/cylp/cpp/IClpPrimalColumnPivotBase.o -w -std=c++11
    In file included from cylp/cpp/IClpPrimalColumnPivotBase.cpp:1:
    cylp/cpp/IClpPrimalColumnPivotBase.h:5:10: fatal error: ClpPrimalColumnPivot.hpp: No such file or directory
     #include "ClpPrimalColumnPivot.hpp"
              ^~~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-me_cix2z/cylp/setup.py'"'"'; __file__='"'"'/tmp/pip-install-me_cix2z/cylp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-dq_87atd/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7m/cylp Check the logs for full command output.

**Comment by tkralphs** [comment]
Looks like this is a Travis build? It would be helpful if you could enumerate all the steps you took, including how you installed Cbc, what version you installed, etc. Cbc should be installed in `/home/travis/build/coin-or/build/` for the above command to properly find the header files for Clp/Cbc that it needs. There is a Docker build that provides the exact steps needed to build CyLP on Ubuntu here:

https://github.com/coin-or-tools/cylp-docker/blob/master/image/Dockerfile

and the Docker image can be obtained here:

https://hub.docker.com/repository/docker/coinor/cylp

**Comment by daiwang369** [comment]
Thanks so much for your reply! Here is the docker file I used. Am I missing any env configuration?
----------------------
FROM ubuntu:latest
FROM python:3.7.8

RUN apt-get update && \
    apt-get install -y \
    apt-utils tar curl pkg-config \
    liblapack-dev \
    libblas-dev \
    freetds-dev

# install cbc
RUN curl -L "https://bintray.com/coin-or/download/download_file?file_path=Cbc-2.10.3-linux-x86_64-gcc4.8.tgz" -o cbc.tar
RUN tar -xvf cbc.tar

# install cylp
RUN pip3 install numpy
RUN pip3 install cylp==0.9.4

**Comment by tkralphs** [comment]
I can't make sense out of your two posts. In your build command, there is a flag `-I/home/travis/build/coin-or/build/include/coin`, which means that `setup.py` somehow thinks that Cbc is install in `/home/travis/build/coin-or/build/`, but your Docker file doesn't mention that directory anywhere, so I can only conclude that the output doesn't come from running the above Docker file. 

Anyway, comparing the two Docker files myself, I see that you are missing the command to set `COIN_INSTALL_DIR`. Alternatively, you can also just set `PKG_CONFIG_PATH`. I don't really know where the curl and tar commands are being executed, so I don't know what directory those environment variables should be set to. I would suggest setting the working directory to make things clearer. 

The easiest solution would be to just modify the working Docker file I posted (or even just use it is as is).

**Comment by tkralphs** [comment]
I'm going to close this issue for now, since there doesn't seem to be anything wrong in CyLP itself. Feel free to reopen if needed.
