### ISSUE TITLE
Segmentation fault for custom pivots

### ISSUE THREAD

**Issue by choidami** [coin-or/CyLP#103]
The unit test test_CyClpSimplex.py fails with a segmentation fault.
More specifically, when I try to solve the p0033.mbs example using DantzigPivot.py and PositiveEdgePivot.py, I get the error.
The code snippet I'm running (executed in the CyLP/cylp folder):

```
from cylp.cy import CyClpSimplex

from cylp.py.pivots import PositiveEdgePivot
from cylp.py.pivots import DantzigPivot

s = CyClpSimplex()
s.readMps('input/p0033.mps')

s.setPivotMethod(DantzigPivot(s))
s.primal()
```

and the output I get is:
```
Clp0006I 0  Obj 0 Primal inf 18.492499 (10) Dual inf 5.5987499e+11 (32)
Segmentation fault (core dumped)
```

This doesn't happen with any of the default primal or dual pivot methods (so if I don't explicitly set the pivot method by setPivotMethod). 

I'm using python 3.7.4 on ubuntu and the most recent version of CBC.

**Comment by tkralphs** [comment]
When you say "most recent version of Cbc," what version exactly?

**Comment by choidami** [comment]
I think it's 2.10.5. The path that contains the cbc.pc file is "coinbrew/build/Cbc/2.10.5"

**Comment by choidami** [comment]
Sorry for the trouble, I realized that I wasn't using `pip install cylp`, I was doing `python setup.py install`. Using pip install fixed my issue. Thanks!
