### ISSUE TITLE
primalVariableSolutionAll didn't suport slack variable

### ISSUE THREAD

**Issue by abdxyz** [coin-or/CyLP#109]
I run a simple code, I find that slack variables in primalConstraintSolution and primalVariableSolutionAll are not the same. Below is my code.

`
import numpy as np
from cylp.cy import CyClpSimplex
from cylp.py.modeling.CyLPModel import CyLPArray

A = [[50, 31], [-3, 2, ]]
b = [250, 4]
c = [-1, -0.64]
l = [1, 0]
u = [10000, 10000]

model = CyClpSimplex()
x = model.addVariable('x', len(c))
A = np.matrix(A)
b = np.matrix(b)
l = CyLPArray(l)
u = CyLPArray(u)
c = CyLPArray(c)
model += (A * x <= b)
model += l <= x <= u
model.objective = c * x

model.primal()
print(model.primalConstraintSolution)
print(model.primalVariableSolutionAll)
print(model.dualConstraintSolution)
print(model.dualVariableSolution)

model.setColumnUpperFirstElements(np.array([1000., 4.]))
model.primal()
print(model.primalConstraintSolution)
print(model.primalVariableSolutionAll)
print(model.dualConstraintSolution)
print(model.dualVariableSolution)
`

and my output is 

Clp0006I 0  Obj -1 Dual inf 1.9599998 (2)
Clp0006I 2  Obj -5.0984456
Clp0000I Optimal - objective value -5.0984456
{'R_1': array([250.,   4.])}
[1.94818653e+000 4.92227979e+000 2.31462827e-152 1.63041663e-322]
{'R_1': array([-0.02031088, -0.00518135])}
{'x': array([0., 0.])}
Clp0006I 0  Obj -5.0984456 Primal inf 0.6148531 (1) Dual inf 1.0362694e+10 (2)
Clp0006I 1  Obj -5.08
Clp0000I Optimal - objective value -5.08
{'R_1': array([250.  ,   0.44])}
[2.52000000e+000 4.00000000e+000 2.31462827e-152 1.63041663e-322]
{'R_1': array([-0.02,  0.  ])}
{'x': array([ 0.  , -0.02])}

**Comment by tkralphs** [comment]
The naming is not too great, but from the output, one can reasonably guess that `primalConstraintSolution` is actually returning the row activity.
```
>>> print(model.primalConstraintSolution['R_1'])
[250.   4.]
>>> print(A*np.matrix(model.primalVariableSolution['x']).transpose())
[[250.]
 [  4.]]
```
whereas `primalVariableSolutionAll` is returning the actual values of the slack variables:
```
>>> print(b.transpose() - A*np.matrix(model.primalVariableSolution['x']).transpose())
[[0.]
 [0.]]
```

**Comment by abdxyz** [comment]
Thanks a lot. Yes, the naming is a little confusing. Values of the dual variables can be got by dualConstraintSolution, while slack by dualVairableSolution.
Another weird thing happened. When I add one more line model.getBasisStatus(). The result changes.

`import numpy as np
from cylp.cy import CyClpSimplex
from cylp.py.modeling.CyLPModel import CyLPArray

A = [[50, 31], [-3, 2, ]]
b = [250, 4]
c = [-1, -0.64]
l = [1, 0]
u = [10000, 10000]

model = CyClpSimplex()
x = model.addVariable('x', len(c))
A = np.matrix(A)
b = np.matrix(b)
l = CyLPArray(l)
u = CyLPArray(u)
c = CyLPArray(c)
model += (A * x <= b)
model += l <= x <= u
model.objective = c * x

model.primal()
#print(model.getBasisStatus())
print(model.primalConstraintSolution)   #row value
print(model.primalVariableSolutionAll)  #row slack

print(model.dualConstraintSolution)     #dual variable
print(model.dualVariableSolution)       #dual slack`

**Comment by tkralphs** [comment]
That is strange. Can you close this issue and open a new one for what you just reported above? Thanks!
