### ISSUE TITLE
License update from EPL 1.0 to EPL 2.0

### ISSUE THREAD

**Issue by snio89** [coin-or/CyLP#121]
Like other COIN-OR projects such as CLP and CBC, updating the license of this project can be simply done by just updating [/master/LICENSE](https://github.com/coin-or/CyLP/blob/master/LICENSE). I understand that there would be not much benefit with this update, unless the GPL compatibility sentence is appended. However, updating the license as the latest one would be nice if its process does not take much time of you.

**Comment by tkralphs** [comment]
Yes, I have now done this in 9d495b6. Thanks!
