### ISSUE TITLE
linux.  error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by cafunechen** [coin-or/CyLP#135]
Dear 
I'm using the latest master commit. 
but the error like :
building 'cylp.cy.CyClpPrimalColumnPivotBase' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/cylp
    creating build/temp.linux-x86_64-3.7/cylp/cpp
    creating build/temp.linux-x86_64-3.7/cylp/cy
    gcc -pthread -B /.../cbcv3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I~/Cbc-2.8.5/Cbc/include/coin -I./cylp/cpp -I./cylp/cy -I/.../miniconda3/envs/cbcv3/lib/python3.7/site-packages/numpy/core/include -I. -I~/../Cbc-2.8.5/Cbc/include/coin -I/../miniconda3/envs/cbcv3/include/python3.7m -c cylp/cpp/IClpPrimalColumnPivotBase.cpp -o build/temp.linux-x86_64-3.7/cylp/cpp/IClpPrimalColumnPivotBase.o -w -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    In file included from cylp/cpp/IClpPrimalColumnPivotBase.cpp:1:0:
    cylp/cpp/IClpPrimalColumnPivotBase.h:5:36: fatal error: ClpPrimalColumnPivot.hpp: No such file or directory
     #include "ClpPrimalColumnPivot.hpp"
                                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1

i see the same question at https://github.com/coin-or/CyLP/issues/71#issuecomment-509336521,but it didn't work .
 thanks

**Comment by tkralphs** [comment]
The problem in #71 is unrelated to what you're seeing here. Your include directory is indicated as `~/Cbc-2.8.5/Cbc/include/coin`. I assume this means are are using Cbc 2.8.5? That is a very old version. Please follow the instructions in the README to either get the most recent release of Cbc or else just install Cbc using your package manager (assuming you are on Debian/Ubuntu/Fedora) and then everything should work.

**Comment by cafunechen** [comment]
> The problem in #71 is unrelated to what you're seeing here. Your include directory is indicated as `~/Cbc-2.8.5/Cbc/include/coin`. I assume this means are are using Cbc 2.8.5? That is a very old version. Please follow the instructions in the README to either get the most recent release of Cbc or else just install Cbc using your package manager (assuming you are on Debian/Ubuntu/Fedora) and then everything should work.

thanks for your patience. i re-install cbc follow the README like 
1.conda create -n cbc python=3.7 coin-or-cbc -c conda-forge. 
2.pip install cylp
and the cbc -v show :
      Welcome to the CBC MILP Solver
      Version: 2.10.5
      Build Date: Nov  3 2021but the same error occurs:

but the same error occurs
...
building 'cylp.cy.CyClpPrimalColumnPivotBase' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/cylp
    creating build/temp.linux-x86_64-3.7/cylp/cpp
    creating build/temp.linux-x86_64-3.7/cylp/cy
    gcc -pthread -B ~/miniconda3/envs/cbc/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I~Cbc/include/coin -I./cylp/cpp -I./cylp/cy -I/~/miniconda3/envs/cbc/lib/python3.7/site-packages/numpy/core/include -I. -I~/Cbc/include/coin -I/~/miniconda3/envs/cbc/include/python3.7m -c cylp/cpp/IClpPrimalColumnPivotBase.cpp -o build/temp.linux-x86_64-3.7/cylp/cpp/IClpPrimalColumnPivotBase.o -w -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    In file included from cylp/cpp/IClpPrimalColumnPivotBase.cpp:1:0:
    cylp/cpp/IClpPrimalColumnPivotBase.h:5:36: fatal error: ClpPrimalColumnPivot.hpp: No such file or directory
     #include "ClpPrimalColumnPivot.hpp"
                                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /~/miniconda3/envs/cbc/bin/python3.7 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-22z5fe8n/cylp_bc01c3d930ad47d798dd9ac51d213f7e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-22z5fe8n/cylp_bc01c3d930ad47d798dd9ac51d213f7e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5gzp3osc/install-record.txt --single-version-externally-managed --compile --install-headers /~/miniconda3/envs/cbc/include/python3.7m/cylp Check the logs for full command output.

**Comment by tkralphs** [comment]
Something looks corrupted in your setup, but if nothing else, you need to active the environment in which you just built cbc and build CyLP in that environment. In other words, in between steps 1 and 2, you need to do `conda activate cbc`. The fact that `cbc -v` works without activating the environment is a bit strange, though, and I suspect you have another version of Cbc installed somewhere that is in your path, which could also cause issues. Just ensure that `which cbc` gives you the path to Cbc that it should before you `pip install cylp`.

**Comment by cafunechen** [comment]
> 
thanks，i did conda activate cbc before pip install cylp.  i'll check if their has another version of cbc. Thank you again

**Comment by tkralphs** [comment]
Hmm, OK, I'm not sure how experienced you are at debugging compiler errors, but the error is that the header file is not being found and if you look at the compiler command line, you can see where it's looking:
``` 
-I~Cbc/include/coin -I./cylp/cpp -I./cylp/cy -I/~/miniconda3/envs/cbc/lib/python3.7/site-packages/numpy/core/include -I. -I~/Cbc/include/coin -I/~/miniconda3/envs/cbc/include/python3.7m
```
Some of those paths look weird. For instance `~Cbc/include/coin` probably doesn't exist and I don't know how that would have gotten there. I guess that the place where the header should be is `~/miniconda3/envs/cbc/include/python3.7m` but that path got somehow corrupted to `/~/miniconda3/envs/cbc/include/python3.7m`, which also wouldn't exist. The argument `-Wl,--sysroot=/` looks suspect to me and could be the issue, but I have no idea where that comes from either. So there seems to be something corrupted somewhere. It doesn't look like a problem with CyLP or Cbc.

**Comment by cafunechen** [comment]
> Hmm, OK, I'm not sure how experienced you are at debugging compiler errors, but the error is that the header file is not being found and if you look at the compiler command line, you can see where it's looking:
> 
> ```
> -I~Cbc/include/coin -I./cylp/cpp -I./cylp/cy -I/~/miniconda3/envs/cbc/lib/python3.7/site-packages/numpy/core/include -I. -I~/Cbc/include/coin -I/~/miniconda3/envs/cbc/include/python3.7m
> ```
> 
> Some of those paths look weird. For instance `~Cbc/include/coin` probably doesn't exist and I don't know how that would have gotten there. I guess that the place where the header should be is `~/miniconda3/envs/cbc/include/python3.7m` but that path got somehow corrupted to `/~/miniconda3/envs/cbc/include/python3.7m`, which also wouldn't exist. The argument `-Wl,--sysroot=/` looks suspect to me and could be the issue, but I have no idea where that comes from either. So there seems to be something corrupted somewhere. It doesn't look like a problem with CyLP or Cbc.

yes, i try it on another linux system ,it works!  It's true that not a problem with CyLP or Cbc.  thanks a lot~ best wishes

**Comment by cafunechen** [comment]
> conda create -n cbc python=3.7 coin-or-cbc -c conda-forge

Hi!  I guess it's because I use conda and compiled binary at the same time; I deleted all folders associated with “CBC” and "coin-or" from the system, and then re-executed, and it work!!!!!! .  
Thank you for your patience. you help me a lot~
