### ISSUE TITLE
Integer variables not being integer

### ISSUE THREAD

**Issue by rsemenoff** [coin-or/CyLP#139]
I create a CyLPModel  for a simple linear problem, then do s=CyClpSimplex  and add a set of integer variable arrays to that (isin0, isin1...)  along with variable constraints 0<isin<1, and bigM contraints. The solution is not correct.

 s.primal() returns optimal, but when I look at s.primalVariableSolution['isin0'] , these
variables are not integer valued, nor do they satisfiy the 0<isin0<1 constraint.
 

Both CyLPModel and CyClpSimplex can set integer variables, but in different ways. I suspect that I'm not designating my integer variables correctly. In the .mps file (see bigMproblem3.mps attached), the integer variables have BV BOUND isin0 1. only (not the >0 part of the constraint) , so it seems that the problem has been set up correctly as far as these variables go, but the solution is incorrect. 

I made a trivial example that replicates this (based on the sample code from the documentation :

import numpy as np
from cylp.cy import CyCbcModel, CyClpSimplex
from cylp.py.modeling.CyLPModel import CyLPModel, CyLPArray
model = CyLPModel()

#X can only solve to 1
x = model.addVariable('x', 3, isInt=True)
model+=x>=0.1

y = model.addVariable('y', 1)#RWS changed from 2 to 1
A = np.matrix([[1., 2., 0],[1., 0, 1.]])
B = np.matrix([[1., 0, 0], [0, 0, 1.]])
#D = np.matrix([[1., 2.],[0, 1]])# RWS deleted
D = np.matrix([[1.],[0]])#RWS added
a = CyLPArray([5, 2.5])
b = CyLPArray([4.2, 3])
x_u= CyLPArray([2., 3.5])
model += A*x <= a
#model += 2 <= B * x + D * y <= b
model += y >= 0
model += 1.1 <= x[1:3] <= x_u
c = CyLPArray([1., -2., 3.])
model.objective = c * x + 2 * y.sum()

s = CyClpSimplex(model)
cbcModel = s.getCbcModel()

cbcModel.solve()
print (cbcModel.status)
s.primalVariableSolution

solution
{'x': array([0., 0., 0.]), 'y': array([0.])}

**Comment by tkralphs** [comment]
I can't say that I really follow the logic of what you're trying to say with this bug report, but when I run your script locally, the command `print(cbcModel.status)` reports `relaxation infeasible` so there is no solution, correct or not.

**Comment by rsemenoff** [comment]
I ran this code in a jupyter notebook, and it does say infeasible, but only in the jupyter server terminal (i.e. stdout), but the python variable in the notebook doesn't indicate that.
My actual application runs in a flask server and it would seem to be the same case there, that errors are reported in the stdout of the flask server, but not making it into the python code where the actual decision is made to use the solver results or not. Maybe that's the only issue then. Are there any alternative ways, in python, to determine if the solver has arrived at a solution or not ?

**Comment by tkralphs** [comment]
It's printing the status to the terminal only because of the `print` command in the script itself. The status is a property in the CycCbcModel class that you can process in your script, e.g.,
```
if not 'infeasible' in cbcModel.status:
   print (s.primalvariableSolution)
   ...
else:
   print ("Instance is infeasible")
   ...
```
I guess maybe the fact that the solution is always printed even though a solution may sometimes now exist is a bit misleading. The string status is printed from the raw status, as you see here:
https://github.com/coin-or/CyLP/blob/e619c4b94e279e96842da0d38ae657f06f1e9415/cylp/cy/CyCbcModel.pyx#L152-L160

**Comment by rsemenoff** [comment]
Yes , the original problem of integer constraints turned out to be user error on my part, and I can simply assert the original problem against the result to detect infeasibility , which is very easy with Python modeling (and more informative) that it's not important to be able to fetch the  status , certainly very low priority

**Comment by tkralphs** [comment]
OK, great!
