### ISSUE TITLE
Lower bound not respected for multidimensional variable in CBC model

### ISSUE THREAD

**Issue by KeithWM** [coin-or/CyLP#141]
Hi,

First of all I'd like to say I'm very happy that you are making this interface to the CBC solver available. I've been using CBC in combination with Pyomo for some  time now, but the interface via LP files is frustratingly slow.

I have been trying to set up a MIP with multidimensional variables, and I run into issues. I can't share the actualy problem, but I think the example below illustrates at least one issue with using multidimensional arrays with a CbcModel.

    import numpy as np
    from cylp.cy import CyCbcModel, CyClpSimplex
    from cylp.py.modeling.CyLPModel import CyLPModel, CyLPArray

    model = CyLPModel()

    x = model.addVariable('x', (2, 3, 2), isInt=True)
    y = model.addVariable('y', (2, 3))

    for i in range(2):
        for j in range(3):
            model += x[i, j, :].sum() - y[i, j] == 0
    model += 1 <= y

    for i in range(2):
        model += x[:, :, i].sum() == 2

    model.objective = x[0, 0]

    s = CyClpSimplex(model)
    cbcModel = s.getCbcModel()
    cbcModel.solve()
    print(cbcModel.primalVariableSolution['y'])
    print(y.lower)

I see rather erratic values for the solution y, even though the lower bound does seem to be set:

    {(0, 0): -15624999999998.0, (0, 1): 15624999999999.0, (0, 2): 3125000000000.0, (1, 0): -3124999999999.0, (1, 1): 3125000000000.0, (1, 2): -3124999999999.0}
    [1. 1. 1. 1. 1. 1.]

Am I doing something wrong? Or is this just an unsupported use case?

**Comment by tkralphs** [comment]
I didn't have a chance to try to replicate this yet, but it's a good idea to print `cbcModel.status` to make sure that the instance isn't infeasible or that there wasn't some other failure. In that case, the solution is still printed but may contain garbage (this should ideally be changed because it causes a lot of confusion). It would also help turn the log level for Cbc up (something like `cbcModel.logLevel = 10` should work) so you can see what the solver is actually doing.

**Comment by KeithWM** [comment]
Hi Ted, Thanks for the suggestion, maybe the only issue was that there was a bug in my (original) model and I misinterpreted the results as meaning that there was something wrong in the multidimensional approach of CyLP for CBC. It's not mentioned in the docs that it would be possible, so I was kind of expecting it not to....

**Comment by tkralphs** [comment]
@KeithWM Is everything working?

**Comment by KeithWM** [comment]
Hi Ted,

Thanks very much checking up! I haven't actually had much time to invest in this line of approach for our case, in the first week of the year things weren't so busy at the office and I could do some more exploratory stuff. But I did indeed discover that the solution was infeasible. I presume that was the only issue. I'll close the issue. If ever needed, I'll open a new one.
