### ISSUE TITLE
Wheel for Python 3.10

### ISSUE THREAD

**Issue by Francois-Bergeron** [coin-or/CyLP#142]
Hi,

I've started a new modeling project and I'm trying to **pip install cylp** in my environment, but there's currently no wheel for Python 3.10.

Any possibilities of releasing a whl for 3.10?

Thanks for all your work!

**Comment by tkralphs** [comment]
There's a fix for Python 3.10 in master, but I haven't had a chance to make a release yet. If you 
```
python -m pip install git+https://github.com/coin-or/CyLP
```
it should work, but you need to have Cbc installed already. If you are looking for a wheel for Windows installation, I'll make one as soon as I have the chance. See also #148 .

**Comment by Francois-Bergeron** [comment]
That's perfect. Thanks!

**Comment by tkralphs** [comment]
There are now also wheels for Python 3.10 available.
