### ISSUE TITLE
Missing 0.91.6 wheels for Windows on PyPI

### ISSUE THREAD

**Issue by brandon-avantus** [coin-or/CyLP#182]
It would be great to have some Windows wheel files for version 0.91.6 on PyPI. This is the only thing blocking our project from moving to Python 3.11. Thanks!

**Comment by tkralphs** [comment]
I just uploaded wheels for 0.91.6 up to Python 3.11. They seem to be working for me. Can you test?

**Comment by tkralphs** [comment]
This seems to be working (see #176), so I'm going to close it.

**Comment by brandon-avantus** [comment]
Thanks for the quick turnaround. I can verify that cylp installs fine now using pip on Python 3.11. But I guess I unknowingly lied about cylp being the only blocker to moving my project to 3.11. The other package, however, is under my control, so should be easy. Thanks again!
