### ISSUE TITLE
DeprecationWarning raised..

### ISSUE THREAD

**Issue by scollis** [coin-or/CyLP#27]
In calling from Py-ART's phase processing engine.. Looks like you call something in Numpy with a float that will soon only accept an integer

/Users/scollis/anaconda/lib/python2.7/site-packages/numpy/core/numeric.py:183: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  a = empty(shape, dtype, order)
/Users/scollis/anaconda/lib/python2.7/site-packages/numpy/lib/twodim_base.py:300: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = zeros((n, n), v.dtype)
/Users/scollis/anaconda/lib/python2.7/site-packages/numpy/lib/twodim_base.py:300: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = zeros((n, n), v.dtype)
/Users/scollis/anaconda/lib/python2.7/site-packages/numpy/lib/twodim_base.py:305: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res[:n-k].flat[i::n+1] = v
/Users/scollis/anaconda/lib/python2.7/site-packages/numpy/lib/twodim_base.py:305: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res[:n-k].flat[i::n+1] = v
/Users/scollis/anaconda/lib/python2.7/site-packages/numpy/lib/twodim_base.py:305: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res[:n-k].flat[i::n+1] = v
/Users/scollis/anaconda/lib/python2.7/site-packages/numpy/core/numeric.py:183: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  a = empty(shape, dtype, order)
/Users/scollis/anaconda/lib/python2.7/site-packages/numpy/lib/twodim_base.py:300: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = zeros((n, n), v.dtype)
/Users/scollis/anaconda/lib/python2.7/site-packages/numpy/lib/twodim_base.py:300: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = zeros((n, n), v.dtype)
/Users/scollis/anaconda/lib/python2.7/site-packages/numpy/lib/twodim_base.py:305: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res[:n-k].flat[i::n+1] = v
/Users/scollis/anaconda/lib/python2.7/site-packages/numpy/lib/twodim_base.py:305: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res[:n-k].flat[i::n+1] = v
/Users/scollis/anaconda/lib/python2.7/site-packages/numpy/lib/twodim_base.py:305: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res[:n-k].flat[i::n+1] = v
/Users/scollis/anaconda/lib/python2.7/site-packages/numpy/core/numeric.py:183: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  a = empty(shape, dtype, order)
/Users/scollis/anaconda/lib/python2.7/site-packages/numpy/lib/twodim_base.py:300: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = zeros((n, n), v.dtype)
/Users/scollis/anaconda/lib/python2.7/site-packages/numpy/lib/twodim_base.py:300: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = zeros((n, n), v.dtype)
/Users/scollis/anaconda/lib/python2.7/site-packages/numpy/lib/twodim_base.py:305: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res[:n-k].flat[i::n+1] = v
/Users/scollis/anaconda/lib/python2.7/site-packages/numpy/lib/twodim_base.py:305: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res[:n-k].flat[i::n+1] = v
/Users/scollis/anaconda/lib/python2.7/site-packages/numpy/lib/twodim_base.py:305: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res[:n-k].flat[i::n+1] = v
/Users/scollis/anaconda/lib/python2.7/site-packages/numpy/core/numeric.py:183: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  a = empty(shape, dtype, order)
/Users/scollis/anaconda/lib/python2.7/site-packages/numpy/lib/twodim_base.py:300: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = zeros((n, n), v.dtype)
/Users/scollis/anaconda/lib/python2.7/site-packages/numpy/lib/twodim_base.py:300: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = zeros((n, n), v.dtype)
/Users/scollis/anaconda/lib/python2.7/site-packages/numpy/lib/twodim_base.py:305: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res[:n-k].flat[i::n+1] = v
/Users/scollis/anaconda/lib/python2.7/site-packages/numpy/lib/twodim_base.py:305: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res[:n-k].flat[i::n+1] = v
/Users/scollis/anaconda/lib/python2.7/site-packages/numpy/lib/twodim_base.py:305: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res[:n-k].flat[i::n+1] = v
/Users/scollis/anaconda/lib/python2.7/site-packages/numpy/core/numeric.py:183: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  a = empty(shape, dtype, order)
/Users/scollis/anaconda/lib/python2.7/site-packages/numpy/lib/twodim_base.py:300: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = zeros((n, n), v.dtype)
/Users/scollis/anaconda/lib/python2.7/site-packages/numpy/lib/twodim_base.py:300: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res = zeros((n, n), v.dtype)
/Users/scollis/anaconda/lib/python2.7/site-packages/numpy/lib/twodim_base.py:305: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res[:n-k].flat[i::n+1] = v
/Users/scollis/anaconda/lib/python2.7/site-packages/numpy/lib/twodim_base.py:305: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res[:n-k].flat[i::n+1] = v
/Users/scollis/anaconda/lib/python2.7/site-packages/numpy/lib/twodim_base.py:305: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  res[:n-k].flat[i::n+1] = v
/Users/scollis/anaconda/lib/python2.7/site-packages/cylp-0.7.1-py2.7-macosx-10.6-x86_64.egg/cylp/py/modeling/CyLPModel.py:372: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if left == None:
/Users/scollis/anaconda/lib/python2.7/site-packages/cylp-0.7.1-py2.7-macosx-10.6-x86_64.egg/cylp/py/utils/sparseUtil.py:388: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if b == None:
/Users/scollis/anaconda/lib/python2.7/site-packages/pyart/correct/phase_proc.py:925: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  s = CyClpSimplex(model)

**Comment by jjhelmus** [comment]
Fixed in PR #23.  No release of CyLP has been made since this fix.
