### ISSUE TITLE
Error when installing CyLP: no member named 'f_tstate' in '_frame'

### ISSUE THREAD

**Issue by kathleenszabo** [coin-or/CyLP#35]
Hi,

I've been trying to install CyLP on my mac and when I run python setup.py install I get the error pasted below. Do you know how to get around this error? I found this link: https://github.com/scikit-learn/scikit-learn/issues/3114 and ran pip install cython https://github.com/scikit-learn/scikit-learn/archive/master.zip as the suggested workaround, but that didn't seem to make any difference and I still get the same error. Is there another way I can get around this?

Thanks!

____________________________________________________________________________
Last login: Sun Mar 27 16:57:54 on ttys001
Kathleen-Szabos-MacBook-Pro:~ admin$ ls
Applications		Movies			anaconda
Desktop			Music			eclipse
Documents		Pictures		setuptools-20.3.1.zip
Downloads		Public
Library			Sites
Kathleen-Szabos-MacBook-Pro:~ admin$ cd Downloads/
Kathleen-Szabos-MacBook-Pro:Downloads admin$ cd CyLP-master
Kathleen-Szabos-MacBook-Pro:CyLP-master admin$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 40, in <module>
    CoinDir = os.environ['COIN_INSTALL_DIR']
  File "/Users/admin/anaconda/lib/python3.5/os.py", line 683, in __getitem__
    raise KeyError(key) from None
KeyError: 'COIN_INSTALL_DIR'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 46, in <module>
    location = dirname(check_output(['which', 'clp']).strip())
  File "/Users/admin/anaconda/lib/python3.5/subprocess.py", line 629, in check_output
    **kwargs).stdout
  File "/Users/admin/anaconda/lib/python3.5/subprocess.py", line 711, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['which', 'clp']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 49, in <module>
    raise Exception('Please set the environment variable COIN_INSTALL_DIR'
Exception: Please set the environment variable COIN_INSTALL_DIR to the location of the COIN installation
Kathleen-Szabos-MacBook-Pro:CyLP-master admin$ export COIN_INSTALL_DIR=/Users/admin/Downloads/Cbc-2.9.8
Kathleen-Szabos-MacBook-Pro:CyLP-master admin$ python setup.py install
/Users/admin/anaconda/lib/python3.5/site-packages/setuptools-20.3.1-py3.5.egg/setuptools/dist.py:285: UserWarning: Normalizing '0.7.4
' to '0.7.4'
running install
cylp/cy/CyClpDualRowPivotBase.cpp:        if (std::isspace(*ts))
cylp/cy/CyCoinModel.cpp:        if (std::isspace(*ts))
cylp/cy/CyDualPivotPythonBase.cpp:        if (std::isspace(*ts))
cylp/cy/CyOsiCuts.cpp:        if (std::isspace(*ts))
cylp/cy/CyPEPivot.cpp:                std::isspace(Py_CHARMASK(s[len-1])) &&
cylp/cy/CyTest.cpp:                std::isspace(Py_CHARMASK(s[len-1])) &&
running build
running build_py
running build_ext
building 'cylp.cy.CyClpPrimalColumnPivotBase' extension
gcc -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/admin/anaconda/include -arch x86_64 -I./cylp/cpp -I./cylp/cy -I/Users/admin/Downloads/Cbc-2.9.8/include/coin -I/Users/admin/anaconda/lib/python3.5/site-packages/numpy/core/include -I. -I/Users/admin/anaconda/include/python3.5m -c cylp/cpp/IClpPrimalColumnPivotBase.cpp -o build/temp.macosx-10.5-x86_64-3.5/cylp/cpp/IClpPrimalColumnPivotBase.o -w
gcc -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/admin/anaconda/include -arch x86_64 -I./cylp/cpp -I./cylp/cy -I/Users/admin/Downloads/Cbc-2.9.8/include/coin -I/Users/admin/anaconda/lib/python3.5/site-packages/numpy/core/include -I. -I/Users/admin/anaconda/include/python3.5m -c cylp/cy/CyClpPrimalColumnPivotBase.cpp -o build/temp.macosx-10.5-x86_64-3.5/cylp/cy/CyClpPrimalColumnPivotBase.o -w
cylp/cy/CyClpPrimalColumnPivotBase.cpp:5019:19: error: no member named
      'f_tstate' in '_frame'
        (*frame)->f_tstate = tstate;
        ~~~~~~~~  ^
1 error generated.
error: command 'gcc' failed with exit status 1

**Comment by tkralphs** [comment]
The same error message is mentioned in #15. This seems to be related to the fact that you are compiling in Python 3. There is an open pull request to add Python 3 support (see #28), which will probably fix the problem.

However, I can also see from the output that you have not set the variable ```COIN_INSTALL_DIR```. Have you first built and installed ```Cbc``` per the instructions [here](https://github.com/coin-or/CyLP#installing-from-source)? You can probably use the latest Cbc rather than the version recommended there.

**Comment by kathleenszabo** [comment]
Hi Ted,

Thanks for responding so quickly! I had forgotten to set the variable COIN_INSTALL_DIR initially, but further in my code I do set it before I end up getting the error – I should have been more selective with my copying from terminal ☺. I do have the latest Cbc version installed so I don’t think that’s the issue.

I appreciate the links. I’m very new to all of this (I took a couple compsci classes in college but have never used github before this project), so I read through #28, but I’m a little unsure where to go from there. Correct me if I’m wrong, but it looks like someone went through the code and adjusted it for later python versions. This may be a silly question, but how do I get those updates on my computer?

Thanks,
Kathleen


--
Kathleen Szabo | Quantitative Economics and Statistics Group

EY
Office: +1 202 327 7446 | kathleen.szabo@ey.com<mailto:kathleen.szabo@ey.com>

**Comment by tkralphs** [comment]
I'm not sure how familiar you are with git, but there are probably a dozen different ways to accomplish this (as usual with git :)). To create a branch that has all the changes, the easiest solution is probably
```
git checkout -b jjhelmus-py3 master
git pull https://github.com/jjhelmus/CyLP.git py3
```
You can then merge those changes back into master with
```
git checkout master
git merge --no-ff jjhelmus-py3
```
although that isn't strictly necessary (it will allow you to continue to pull from master in the future if there are other changes).

**Comment by jjhelmus** [comment]
You can also download a zip file containing the py3 branch from https://github.com/jjhelmus/CyLP/archive/py3.zip if you do not want to mess with git.

**Comment by kathleenszabo** [comment]
I ended up downloading the zip file and using that seems to have solved the issue. Thanks so much!

**Comment by kvak** [comment]
@jjhelmus : is this still the current way to get (experimental) py3 support for cypl? (https://github.com/jjhelmus/CyLP/tree/py3_rebase seems more recent)

Thanks! (I'm really looking forward to experiment with cypl & test it with https://github.com/bradfordboyle/pyglpk but the rest of the code is in py3)

**Comment by jjhelmus** [comment]
> @jjhelmus : is this still the current way to get (experimental) py3 support for cypl? (https://github.com/jjhelmus/CyLP/tree/py3_rebase seems more recent)

I would still use the `py3` branch.  The `py3_rebase` branch was a rebase of that branch upon the latest master but I can't recall if it is complete or not.

**Comment by kvak** [comment]
@ jjhelmus thanks for your answer

**Comment by kvak** [comment]
@jjhelmus  I encounter a problem with the `py3` branch (the  CyLP master branch does not have this problem).
When I download https://github.com/jjhelmus/CyLP/archive/py3.zip unpack it in a folder called `cycl` and run `easy_install cyclp` I get:

```
Processing cyclp
Writing /home/kvak/Downloads/cyclp/setup.cfg
Running setup.py -q bdist_egg --dist-dir /home/kvak/Downloads/cyclp/egg-dist-tmp-Vk9mUs
error: [Errno 2] No such file or directory: '/home/kvak/Downloads/Cbc-2.9.8/share/coin/doc/Cbc/cbc_addlibs.txt'
```

the same procedure works when I use CyLP master (https://github.com/coin-or/CyLP/archive/master.zip). 

would you know what is causing this?

Thanks in advance,

**Comment by tkralphs** [comment]
It seems that maybe you have the variable `COIN_INSTALL_DIR` set to `/home/kvak/Downloads/Cbc-2.9.8`, which look as though it's not actually the location of the install. There is a bit of extra logic in `master` that was suggested in PR #16 to automatically detect the location of the install if the variable is unset of set incorrectly. That is probably why it works in `master`. You could probably just merge master into the `py3` branch or just cheery-pick the commit that merge the PR if you want the same thing. Otherwise, setting the value of `COIN_INSTALL_DIR` should do the trick.
