### ISSUE TITLE
CyLP : in-memory computations or via .mps/.lp

### ISSUE THREAD

**Issue by samiit** [coin-or/CyLP#40]
I wanted to know whether CyLP calls Cbc via in-memory computations (like JuMP) or does it follow the path of PuLP, i.e., writing a .mps file and then calling the Cbc executable with an .mps input?

**Comment by tkralphs** [comment]
Yes, CyLP is implemented as a C extension and thus the communication with the solver library is in-memory like JuMP. There really isn't much choice but to do it this way, since CyLP provides low-level access to solver internals and also allows implementation of callbacks in Python.

**Comment by samiit** [comment]
Thanks Ted. Can you please direct me to the place where you call the C library of CBC in CyLP code? Specifically, what data structure is passed as argument for the model to the CBC function? Which function?

Thanks,

Sam

**Comment by tkralphs** [comment]
Hmm, I guess the best answer to your question depends a bit on your knowledge of Python, Cython, C++, and Cbc. CyLP consists mainly of two parts: the direct interfaces to Clp and Cbc, which are semi-automatically generated using Cython and some additional python that enables building models in Python to pass in to Cbc and Clp. The wrapper code that creates the interfaces is contained here:

https://github.com/coin-or/CyLP/tree/master/cylp/cy

You see three files for each file in the Clp and Cbc. The python classes that you would directly use are in the `.pyx` files. To load a model into Cbc and solve it, you would use the `CyCbcModel` class here:

https://github.com/coin-or/CyLP/blob/master/cylp/cy/CyCbcModel.pyx

Note that this requires first loading your model into CyClpSimplex and then passing this to CyCbcModel. How to do this is well-documented in the course file. Hope this helps. Of course, there are multiple ways of getting a model into Cbc with CyLP and each would use different intermediate data structure. To really get a feel for how the whole thing works, it's easiest to start using it and then trace the path the data takes for your use case. Feel free to ask if you have more questions.
