### ISSUE TITLE
Create constraints using sparse matrices

### ISSUE THREAD

**Issue by dafinguzman** [coin-or/CyLP#45]
I would like to use sparse matrices when defining constraints, as the memory allocation of the equivalent numpy matrices is too large for my capacities. 
Is this too difficult to implement, given the current state of `CyLPModel.py`?  I am using version 0.7.4.

**Note:** I tried to use a `lil_matrix` from the `scipy.sparse`module and I got the following error in the line ` model += sp_matrix * x <= 1`:
```
  File "/usr/lib/python2.7/dist-packages/scipy/sparse/base.py", line 344, in __mul__
    raise ValueError('could not interpret dimensions')
```

**Comment by gdalle** [comment]
Hi ! The library CyLP does indeed accept sparse matrices for the definition of constraints, but you have to use their own implementation of sparse matrices : http://mpy.github.io/CyLPdoc/modules/sparseUtil.html
Good luck :)

**Comment by sschnug** [comment]
I never checked the code, but sparse-matrices seem to be supported out-of-the-box! I use it all the time.

Some examples are available [here](https://github.com/sschnug/footrule_ranking) and [here](https://github.com/sschnug/kemeny_ranking) (while the latter is more advanced in terms of numpy/scipy usage to make constraint-building efficient!).

So in general this should work:

    model += lhs * x == rhs (where lhs is of type scipy.sparse)

Actually this won't work for lhs of type numpy-array. I never did try it, but a short look at the code looks like it's completely build on np.matrix in this regards (so it should work for this type).
