### ISSUE TITLE
select MILP solver CBC, lp_solve, Gurobi, cplex, ...

### ISSUE THREAD

**Issue by andresbh** [coin-or/CyLP#49]
it would be nice to be able to choose the solver. 
I like cylp's modeling capabilities better than those of in other modeling libs e.g. pulp, pyomo.

**Comment by tkralphs** [comment]
A primary way in which CyLP is different from other modeling languages is in the fact that it allows direct access to some solver internals (basis inverse, etc.). It would be difficult to extend this to other solvers that don't provide this access to internals. Also, CyLP is in large part just an automatically generated wrapper around the API of Cbc/Clp. This wrapper is not generic like [OSI](https://github.com/coin-or/OSI) is. The modeling language itself is actually pure Python and I suppose it would be possible to use that part of CyLP with other solvers, but I guess that functionality is not very different from what one can do in PuLP or Pyomo. Given how much other stuff is open here, I doubt this will happen. 

If you just want a low-level API to get data from Python into a solver, you could check out [yaposib](https://github.com/coin-or/yaposib), which does provide a generic API for solvers from Python which is a wrapper around [OSI](https://github.com/coin-or/OSI).
