### ISSUE TITLE
Constant Error CyLP install

### ISSUE THREAD

**Issue by LUISSMR** [coin-or/CyLP#55]
Hi Dear All,

I am driving crazy because I have tried to install CyLP and I get the next statement:

MacBook-Pro-de-LUIS:~ luissanmartin$ export COIN_INSTALL_DIR=/Users/luissanmartin/Desktop/Cbc-2.9.6
MacBook-Pro-de-LUIS:~ luissanmartin$ cd /Users/luissanmartin/Desktop/CyLP
MacBook-Pro-de-LUIS:CyLP luissanmartin$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 86, in <module>
    libs = get_libs()
  File "setup.py", line 57, in get_libs
    'doc', 'Cbc', 'cbc_addlibs.txt')) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/luissanmartin/Desktop/Cbc-2.9.6/share/coin/doc/Cbc/cbc_addlibs.txt'

I have installed the Cbc successfully, but I cannot manage with this CyLP issue... may you give some idea about my failure??

Best Wishes!!

Luis

**Comment by HandsomeKevinHo** [comment]
I actually have the same problem like you.
I have also installed the Cbc successfully but in conda. And, when I try to install CyLP, I get the same statement.
Have you solved the problem now? If you installed the CyLP successfully, can you tell me how to solve the problem?

Thanks in advance.

Kevin

**Comment by tkralphs** [comment]
@HandsomeKevinHo Can you tell me exactly how you installed Cbc? What conda recipe did you use? Where is Cbc installed? Did you set `COIN_INSTALL_DIR`? If you are getting the exact same error, the first thing is to look for the file that is missing. Is it there? It's possible the conda recipe is installing things in a non-standard way or else not installing all the files. 

@LUISSMR If the file `/Users/luissanmartin/Desktop/Cbc-2.9.6/share/coin/doc/Cbc/cbc_addlibs.txt` is not there, then you must not have installed `Cbc` in that directory successfully. Perhaps it is installed in a build directory, like `/Users/luissanmartin/Desktop/Cbc-2.9.6/build`? If so, you've set `COIN_STALL_DIR` incorrectly.

**Comment by HandsomeKevinHo** [comment]
@tkralphs Thank you for your reply.
I read the install guide and installed Cbc through Homebrew. And, The Cbc was installed in the "Users/kevin/anaconda3/pkg3/cbc-2.8.8-1" automatically. Sure, I also followed the guide to set COIN_INSTALL_DIR by "export COIN_INSTALL_DIR=/Users/kevin/anaconda3/pkgs/cbc-2.8.8-1".
Now, after I tried to install CyLP again, I got the new error as follows:

In file included from cylp/cpp/IClpPrimalColumnPivotBase.cpp:1:
    ./cylp/cpp/IClpPrimalColumnPivotBase.h:2:10: fatal error: 'iostream' file not found
    #include <iostream>
             ^~~~~~~~~~
    1 error generated.
    error: command 'gcc' failed with exit status 1
    
--------------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;__file__='/private/var/folders/w7/npq83gl54fjdbhf6tbb85rlh0000gn/T/pip-install-F_5vZ3/cylp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/w7/npq83gl54fjdbhf6tbb85rlh0000gn/T/pip-record-F89xns/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/w7/npq83gl54fjdbhf6tbb85rlh0000gn/T/pip-install-F_5vZ3/cylp/
------------------------------------------- 
Do you know how to solve this new problem?

**Comment by tkralphs** [comment]
I'm not sure, that is strange. If you can give some more information about what you're doing, it would be very helpful. What version of CyLP, how your downloaded it, what compiler and what version you are building with, what command you used to build it, what version of Python (looks like 2.7?), etc. I would suggest at the least that you switch to Python 3, which should now work fine with CyLP master.

**Comment by tkralphs** [comment]
The problem originally reported with this PR should be fixed now with the newest version of setup.py (see ddff1a3).
