### ISSUE TITLE
Installing cylp on windows

### ISSUE THREAD

**Issue by mandy8055** [coin-or/CyLP#56]
I am trying to install cylp package on windows. I have tried to do it with pip package using:

>pip install -i https://pypi.anaconda.org/pypi/simple cylp

but my efforts went in vein.Is this package available for windows and if yes How could I install it on windows?

**Comment by andresbh** [comment]
Try the following
Create a new environment for 32bit Python 2.7:

`set CONDA_FORCE_32BIT=1`
`conda create -n py27_32 python=2.7`

Activate it:

`set CONDA_FORCE_32BIT=1`
`activate py27_32`

install cylp:
`conda install scipy`
`pip install cylp`
