### ISSUE TITLE
comparison to `None` will result in an elementwise object comparison in the future.

### ISSUE THREAD

**Issue by hzzyyy** [coin-or/CyLP#58]
Hi,

CyLP is such a nice work that immediately relieved me from the heavy work of using clp as a C++ library.

I was trying the first example in the official documentation and got the following warning:

ipykernel/__main__.py:8: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.

It seems that inside CyLP,  a numpy array is tested for None.
It should be a simple fix by replacing '== None' with 'is None'.

Keep up with the good work!

**Comment by tkralphs** [comment]
This should be fixed by #23 in master.
