### ISSUE TITLE
Memory leak from repeated CyClpSimplex instantiations

### ISSUE THREAD

**Issue by battery-al** [coin-or/CyLP#60]
I have a program that repeatedly instantiates CyClpSimplex objects (ideally solving tens of thousands of LPs), but my kernel kills the program after ~6000 iterations. I think this is because these CyClpSimplex objects are not being freed from memory. In fact, the CyClpSimplex class's __dealloc__ function is commented out in the source. I have already switched to GLPK to get around this problem, but I figured I should call attention to it here in case anyone else ever encounters it.

**Comment by nekrald** [comment]
Issue seems important. If the author can respond where is the problem and what is the idea of fix (why just uncommenting not helps), I can try to contribute with fix. You can PM me in that case.

**Comment by braginpavel** [comment]
I have this bug too when I am using CyLP for repeated LPs. Here it the part of my code, which creates a solver instance, solving LP and finally destroys it:

`       solver = CyClpSimplex()
        x_var = solver.addVariable('x', len(margin))
        # Add constraints
        A = self.A_ub
        b = CyLPArray(b_ub)
        solver += A * x_var <= b
        solver += x_var >= 0
        # Set the objective function
        c = CyLPArray(margin)
        solver.objective = -c * x_var
        solver.primal()
        out = solver.primalVariableSolution['x']
        del solver`

Each 10 iterations I am using gc.collect(), but even in this case consumption of RAM increasing gradually until all of the 12 Gb of RAM become occupied, which completely freezes my machine. I have Linux Fedora 30, CyLP version '0.9.0b1', Clp version 1.16.10.

**Comment by braginpavel** [comment]
I have a same issue with repeated LP's. Here is the part of my code, which creates CyClpSimplex, solving LP and destroying the solver object:

`      solver = CyClpSimplex()
        x_var = solver.addVariable('x', len(margin))
        # Add constraints
        A = self.A_ub
        b = CyLPArray(b_ub)
        solver += A * x_var <= b
        solver += x_var >= 0
        # Set the objective function
        c = CyLPArray(margin)
        solver.objective = -c * x_var
        solver.primal()
        out = solver.primalVariableSolution['x']
        del solver`

Every 10 iterations I am using gc.collect(). But after few thousands of such iterations all of my 12 Gb of RAM becomes occupied, which completely freezes my machine.

**Comment by tkralphs** [comment]
This should be addressed by the #97.
