### ISSUE TITLE
ModuleNotFoundError: No module named 'cylp.cy.CyCoinIndexedVector'

### ISSUE THREAD

**Issue by fuxiocteract** [coin-or/CyLP#72]
After cloned CyLP master branch, and locally installed to virtualenv via python setup.py install, 

When running with code:
`
        cy_solver = CyClpSimplex()
        cy_solver.readMps(TEST_FILE)
`

The following exception is thrown:
`
 File "/Users/shuohuang/Projects/CyLP/cylp/cy/__init__.py", line 1, in <module>
    from .CyCoinIndexedVector import CyCoinIndexedVector
ModuleNotFoundError: No module named 'cylp.cy.CyCoinIndexedVector'
`

**Comment by tkralphs** [comment]
What version of Python, what OS, what version of CBC, etc.? Could you attach the output of the `install` command?

**Comment by fuxiocteract** [comment]
Python 3.7.3, macOS 10.15 beta5, CBC is version 10.21_1

**Comment by tkralphs** [comment]
Are you using Homebrew Python? How are you getting/installing Cbc? That version number is not a Cbc version number.

**Comment by vahidnourbakhsh** [comment]
Is there any update on this bug? I also see the same bug. 
versions:
cylp: 0.9.0b1
cbc: 2.10.2

**Comment by tkralphs** [comment]
I need more information to figure out what's going on, since I so far cannot replicate. I guess you are using the beta version on Pypi? I committed a fix to `master` and was waiting for conformation that this worked. Can you try installing the latest version in `master`?

**Comment by vahidnourbakhsh** [comment]
I cloned the repo, created a python 3 venv (3.6.7 particularly), installed `cbc` successfully and then tried to install `cylp` which failed. I am running it on OSX. 

PS. I do not see any changes to master recently (since a few days ago that I cloned the repo). The last commit goes back to July. Can you confirm that?

**Comment by tkralphs** [comment]
Are you using Homebrew Python? I will try to replicate. Yes, the last commit was in July, but I wanted to make sure you hadn't gotten the source from PyPi, which was uploaded before that last commit (I should have changed the version number in the repo).

**Comment by jonrkarr** [comment]
I see the same problem
- Ubuntu 18.04.3
- Python 3.7.6
- Cbc 2.8.5
- CyLP f99d1c4c7dc12e7bb0005d73d581613055f2429a
- Numpy 1.18.1
- SciPy 1.4.1
- Cython 0.29.14

I see the same problem with 9f3d6bcfb610aea36f108538291c166783b6d6bf

**Comment by tkralphs** [comment]
I've asked for additional information each time this has been reported in the hope of replicating it, but so far, no one has answered, which makes it a bit difficult to address. @jonrkarr Thanks for reporting the commit you tried, but can you say if you are you using Homebrew to install Cbc and/or Python? That is a very old version of Cbc you're using. I would first suggest installing the most recent one with Homebrew, although this doesn't seem likely to fix the problem. Everything works fine for me when installing all dependencies with Homebrew. That is the typical and recommended way to install.

**Comment by jonrkarr** [comment]
I installed Cbc from source. I can use another version. What is the latest compatible version? From early installation troubles, I was under the impression that Cbc was only supported up to 2.8.5.

**Comment by tkralphs** [comment]
CyLP should work with the latest Cbc. Are you using Homebrew to install Python?

**Comment by jonrkarr** [comment]
Python is compiled from source.

I also tried installing Cbc 2.9.9 from apt to no avail.

Note, I previously have setup CyLP (py3 branch from jjhelmus) with
- Ubuntu 18.04.2
- Python 3.6.8 compiled from source
- Cbc 2.8.5
- Cython 0.29.6
- Numpy 1.16.2
- Scipy 1.2.1

I assume the breaking change is upgrading Python 3.6.8 to 3.7.6

**Comment by tkralphs** [comment]
Oops, sorry, the original reporter was on OS X, but I just realized you said you are on Linux. It's possible that the breaking change is in moving to Python 3.7, although CyLP works fine with Python 3.7 on Windows. I'll install Python 3.7.6 on Unbuntu myself and see if I can replicate. In the meantime, CyLP does work for me on Ubuntu 18.04.1 with default versions of Python and all dependenct packages, along with Cbc 2.10.

**Comment by tkralphs** [comment]
The following worked for me to install CyLP from scratch in a clean virtual environment on Ubuntu 18.04.1 (using `pyenv` to install Python from source).
```
cd $HOME
pyenv install 3.7.6
pyenv local 3.7.6
pip install virtualenv
python -m virtualenv $HOME/python-env/py3.7.6
source $HOME/python-env/py3.7.6/bin/activate
pip install numpy
pip install scipy
pip install cython
git clone https://github.com/coin-or/coinbrew
cd coinbrew
./coinbrew fetch Cbc
./coinbrew build Cbc --no-prompt
export LD_LIBRARY_PATH=$HOME/coinbrew/build/lib
export COIN_INSTALL_DIR=$HOME/coinbrew/build
pip install git+git://github.com/coin-or/CyLP
```
The only difference from your installation that I can see are (1) the version of Cbc is the current master version (latest release should also work) and (2) the versions of `numpy` and `scipy` installed were not the same as the ones you installed, as those versions don't seem to be have wheels available for Linux. I guess there are better ways of getting `numpy` and `scipy` on Ubuntu, but I wanted to keep the installation as clean as possible and this at least gives you something to go on. Perhaps you can see if this works for you and then tease out what is actually causing the problem.

**Comment by jonrkarr** [comment]
Thanks. I think the main difference is using a newer version of Cbc from coinbrew. I'll try that.

**Comment by tkralphs** [comment]
OK, let me know how it goes. FYI, there was a small mistake in the list of commands above that I just fixed in case you run into problems.

**Comment by tkralphs** [comment]
I've been unable to replicate this issue and it appears to most likely be due to using an old version of Cbc, so closing for now. Feel free to open again if the issue arises.

**Comment by spkelle2** [comment]
I was able to replicate this error. I resolved it by changing `cylp.cy.__init__.py` to absolute imports.

**Comment by tkralphs** [comment]
Sure, a PR for this would be great!
