### ISSUE TITLE
Thoughts to have CyLP on conda-forge

### ISSUE THREAD

**Issue by zssherman** [coin-or/CyLP#77]
Hello,

So I was thinking, it might be a worth while endeavour to get CyLP on conda-forge https://conda-forge.org/ similar to coincbc, Py-ART, numpy etc. Probably would make the installation process much easier and managing environments better. I began testing some conda building with it, but the most recent pypi version has older cython generated files so conda-build fails. Questions I have are, is there desire to have CyLP on conda-forge? If so, would it be possible to have a pypi release that reflects the most recent github changes? I can then maybe take a whack at it and see if I can get a build going. Just some thoughts etc.

**Comment by tkralphs** [comment]
I've been off working on other things and was waiting for a little more feedback on a couple of reported problems before putting out an official Pypi release of the Python 3 version. @zssherman, you might have a better feel for the state of things than I do. There were a couple of problems reported with the current pre-release version and it was hard to tell if it was user error or what. Based on feedback from your users, does it seems as though everything is working well with the current version on `master`? I guess the reports have been few enough by now that it's best just to make a release on Pypi and deal with whatever additional reports come in after the fact. 

I don't actually know that much about conda-forge. It seems like something we would want and I've actually had on my list for a long time to look into making conda packages of other COIN-OR projects, just hasn't bubbled up yet. I was just poking around in the `coincbc` repo on conda-forge and it looks like it only works on Linux and OSX. It also seems to use the legacy build system, which won't work for much longer. I couldn't quickly really see quickly how the whole thing hangs together.

Anyway, let me know  what you think the best plan of attack is and then we can try to move this along. Thanks!

**Comment by zssherman** [comment]
@tkralphs No worries at all, and makes sense for the Python 3 release. With our users, the issue tends to be setting the environment path for coin or having compiler issues. I figured with anaconda having their own compilers and having a anaconda environment, might be overall simpler to install CyLP with anaconda. Users on our end see to have no issue running the code itself, but just really getting it installed.

I think a stable release with python3 on pypi would be the next step, but waiting on feedback as you mentioned is a good call. Once its release, I can test with anaconda compilers and conda skeleton to see if I can conda build CyLP. If successful, I can look into creating a feedstock. The path setting with export in CyLP might be my only concern, but this might be ok, with coincbc already being in that same conda environment. I think conda-forge is amazing and having CyLP on conda-forge would be great for users. Thank you! Tagging @scollis

**Comment by mckib2** [comment]
Hi, has there been any movement on this?  I'd be interested in seeing CyLP available on conda-forge

**Comment by tkralphs** [comment]
This is still on my radar, but I'd like to have the Cbc stack  on conda-forge first and there are some issues to be addressed there (see conda-forge/coincbc-feedstock#37). I just registered a ping over there, let's see if we can move things forward.

**Comment by tkralphs** [comment]
Just FYI, you can now install Cbc with conda on Linux and OS X, after which `pip install cylp` works out of the box (on Windows, there is a binary wheel, so this is not an issue). Is there any reason to have a conda install for `cylp` itself?

**Comment by mckib2** [comment]
I have no preference for a conda install for `cylp` if dependencies for the pip package can be installed via conda.  This looks great, thanks for pinging this thread!

**Comment by tkralphs** [comment]
FYI: https://github.com/conda-forge/staged-recipes/pull/14950

**Comment by tkralphs** [comment]
I'm going to close this issue now, seeing as there is a recipe in process and pip install also works fine, once `coin-or-cbc` is conda installed.
