### ISSUE TITLE
setup.py directory structure does not match homebrew directory structure

### ISSUE THREAD

**Issue by JDonadee** [coin-or/CyLP#80]
I'm trying to install CyLP on MacOS so that I can use cbc with cvxpy. I used homebrew to install cbc, and added path to the environment variable COIN_INSTALL_DIR, but I got the following error when using pip to install cylp:
`FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/Cellar/cbc/2.10.2_1/share/coin/doc/Cbc/cbc_addlibs.txt'`

The issue appears to be that the file structure doesn't match the expectation of CyLP's setup.py. The files installed by homebrew are actually in the directory `/usr/local/Cellar/cbc/2.10.2_1/share/cbc/coin/doc/Cbc`

**Comment by tkralphs** [comment]
With Homebrew installation, you should not need to set `COIN_INSTALL_DIR`, as the packages are found using `pkg-config`, which is automatically set up when packages are installed. Try installing without setting `COIN_INSTALL_DIR`.

**Comment by tkralphs** [comment]
I just updated the documentation to reflect this. Let me know if it works.

**Comment by JDonadee** [comment]
Thank you for the quick response!
I cleared the `COIN_INSTALL_DIR` variable, but I now get the error:
` FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/share/coin/doc/Cbc/cbc_addlibs.txt'
    ----------------------------------------`
My directory `/usr/local/share/` does not contain a folder `coin`. But there are directories such as `usr/local/share/cbc/coin/doc/Cbc/`

to install cbc, I used the following commands in the terminal
`% brew tap coin-or-tools/coinor
% brew install cbc`

Did I miss something?

**Comment by tkralphs** [comment]
Are you installing from a git clone of this repository in Python 3? Some of the recent fixes may not be in the pre-release version. I was able to install just now on OSX with
```
git clone https://github.com/coin-or/CyLP
cd CyLP
pip3 install . 
```
after editing `setup.py` to comment out the commands imported from `fixBinaries.py`, as follows
```
#        if operatingSystem == 'mac':
#            from fixBinaries import platform_dir
#            extra_files.append(join('cbclibs', platform_dir, '*.dylib'))

        install.run(self)

#        if operatingSystem == 'mac':
#            from fixBinaries import fixAll
#            fixAll()
```
Those were added at some point to fix some issue with the OS X build, but they don't work without `COIN_INSTALL_DIR` set and don't seem to be necessary anyway.

**Comment by JDonadee** [comment]
This did the trick, thank you!
