### ISSUE TITLE
The same solution returned for all two-dimensional variables

### ISSUE THREAD

**Issue by xrust01** [coin-or/CyLP#84]
I have a problem with getting a solution back from the model. We have 11
variables which are two dimensional (for example production in some hour
of some plant) and 6 variables with only one value (total costs). The
model is solved successfully, but we cannot obtain optimal variable
values correctly.

The thing is, that for these two dimensional variables, we obtain the
same variable values. (See enclosed figure). There, sol1 was obtained
from

sol1 = Model.primalVariableSolution

dualVariableSolution attribute shows similar thing, while
ConstraintSolutions appear to be working allright, while the one-dimensinal variabes also appear to have reasonable values.

I attach a screensht from pycharm and also the model formulation.
[StackModel.lp.txt](https://github.com/coin-or/CyLP/files/4138080/StackModel.lp.txt)
![SameSolutions](https://user-images.githubusercontent.com/36644962/73520873-ecb40480-4404-11ea-80e2-bad7c3da2fea.PNG)

**Comment by xrust01** [comment]
I looked into more detail of it and it appears to me there might be problems with some pointer when returning a solution of a CyLpSimplex with variable structure.

See below a minimal example, where first, I define problem s with two (2x2) variables x and y. The problem is solved correctly (optimal value -20, with x = 2 and y = 1), but solution returned from s.primalVariableSolution is x = 2 and y = 2.

When I read the file through readLp, its read without a structure, solved correctly and solution returned correctly in one np.array.  However, one can imagine that for larger problems such that the one I listed above, retrieving the solution values from such a large np.array is very uncomfortable.

Note that primalConstraintSolution works well.

import numpy as np
from cylp.cy import CyClpSimplex
from cylp.py.modeling.CyLPModel import CyLPArray

s = CyClpSimplex()

# Add variables
x = s.addVariable('x', (2,2))
y = s.addVariable('y', (2,2))

s += x >= 0
s += y >= 0
s += x <= 2
s += y <= 4
s += x + y <= 3
s += x - y <= 1

s.objective =  -2 * x.sum() - y.sum()
s.writeLp('Example.lp')

s.dual()
print(s.primalVariableSolution['x'])
print(s.primalVariableSolution['y'])

s2 = CyClpSimplex()
s2.readLp('Example.lp')
s2.dual()
print(s2.primalVariableSolution)

print(s.primalConstraintSolution)
print(s2.primalConstraintSolution)

**Comment by tkralphs** [comment]
Hmm, interesting, thanks for the minimal example, that helps a lot. I'll see if I can find out what's going on.

**Comment by tkralphs** [comment]
OK, I tracked this down and made a new release. In the very particular case of two separate dictionaries of multi-dimensional variables, the mapping between the multi-dimensional indices in the original model and Cbc's single-dimensional indices was broken. Both sets of variables ended up pointing into the same range (as you noticed).
