### ISSUE TITLE
LP formulation for dual solution

### ISSUE THREAD

**Issue by xrust01** [coin-or/CyLP#87]
Hello, 
I would like to ask whether there is some reference for the formulation used for model solution, so I can better understand the model output? I am bit confused with implementation of constraints in the model..

assume a model

<a href="https://www.codecogs.com/eqnedit.php?latex=\begin{align*}&space;\min_{x_{1},x_{2}}&space;&-2x_{1}&space;-&space;x_{2}&space;\\&space;\mathrm{s.t.}&space;\hspace{1&space;em}&space;&x_{1}&space;&plus;&space;x_{2}&space;\leq&space;3&space;\\&space;&0&space;\leq&space;x_{1}&space;\leq&space;2,&space;0&space;\leq&space;x_{2}&space;\end{align*}&space;\hspace{2&space;em}&space;\Leftrightarrow&space;\hspace{2&space;em}&space;\begin{align*}&space;\min_{x_{1},x_{2}}&space;&&space;\begin{pmatrix}&space;-2&space;&&space;-1\end{pmatrix}\begin{pmatrix}&space;x_{1}&space;\\&space;x_{2}\end{pmatrix}&space;\\&space;\mathrm{s.t.}&space;&\begin{pmatrix}&space;1&space;&&space;1&space;\\&space;1&space;&&space;0&space;\end{pmatrix}\begin{pmatrix}&space;x_{1}&space;\\&space;x_{2}\end{pmatrix}&space;\leq&space;\begin{pmatrix}&space;3&space;\\&space;2\end{pmatrix}\\&space;&&space;x_{1},&space;x_{2}&space;\geq&space;0&space;\end{align*}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\begin{align*}&space;\min_{x_{1},x_{2}}&space;&-2x_{1}&space;-&space;x_{2}&space;\\&space;\mathrm{s.t.}&space;\hspace{1&space;em}&space;&x_{1}&space;&plus;&space;x_{2}&space;\leq&space;3&space;\\&space;&0&space;\leq&space;x_{1}&space;\leq&space;2,&space;0&space;\leq&space;x_{2}&space;\end{align*}&space;\hspace{2&space;em}&space;\Leftrightarrow&space;\hspace{2&space;em}&space;\begin{align*}&space;\min_{x_{1},x_{2}}&space;&&space;\begin{pmatrix}&space;-2&space;&&space;-1\end{pmatrix}\begin{pmatrix}&space;x_{1}&space;\\&space;x_{2}\end{pmatrix}&space;\\&space;\mathrm{s.t.}&space;&\begin{pmatrix}&space;1&space;&&space;1&space;\\&space;1&space;&&space;0&space;\end{pmatrix}\begin{pmatrix}&space;x_{1}&space;\\&space;x_{2}\end{pmatrix}&space;\leq&space;\begin{pmatrix}&space;3&space;\\&space;2\end{pmatrix}\\&space;&&space;x_{1},&space;x_{2}&space;\geq&space;0&space;\end{align*}" title="\begin{align*} \min_{x_{1},x_{2}} &-2x_{1} - x_{2} \\ \mathrm{s.t.} \hspace{1 em} &x_{1} + x_{2} \leq 3 \\ &0 \leq x_{1} \leq 2, 0 \leq x_{2} \end{align*} \hspace{2 em} \Leftrightarrow \hspace{2 em} \begin{align*} \min_{x_{1},x_{2}} & \begin{pmatrix} -2 & -1\end{pmatrix}\begin{pmatrix} x_{1} \\ x_{2}\end{pmatrix} \\ \mathrm{s.t.} &\begin{pmatrix} 1 & 1 \\ 1 & 0 \end{pmatrix}\begin{pmatrix} x_{1} \\ x_{2}\end{pmatrix} \leq \begin{pmatrix} 3 \\ 2\end{pmatrix}\\ & x_{1}, x_{2} \geq 0 \end{align*}" /></a>

Then the dual formulation is 

<a href="https://www.codecogs.com/eqnedit.php?latex=\begin{align*}&space;\max_{y_{1},y_{2}}&space;&&space;\begin{pmatrix}&space;3&space;&&space;2\end{pmatrix}\begin{pmatrix}&space;y_{1}&space;\\&space;y_{2}\end{pmatrix}&space;\\&space;\mathrm{s.t.}&space;&\begin{pmatrix}&space;1&space;&&space;1&space;\\&space;1&space;&&space;0&space;\end{pmatrix}\begin{pmatrix}&space;y_{1}&space;\\&space;y_{2}\end{pmatrix}&space;\leq&space;\begin{pmatrix}&space;-2&space;\\&space;-1&space;\end{pmatrix}\\&space;&&space;y_{1},&space;y_{2}&space;\leq&space;0&space;\end{align*}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\begin{align*}&space;\max_{y_{1},y_{2}}&space;&&space;\begin{pmatrix}&space;3&space;&&space;2\end{pmatrix}\begin{pmatrix}&space;y_{1}&space;\\&space;y_{2}\end{pmatrix}&space;\\&space;\mathrm{s.t.}&space;&\begin{pmatrix}&space;1&space;&&space;1&space;\\&space;1&space;&&space;0&space;\end{pmatrix}\begin{pmatrix}&space;y_{1}&space;\\&space;y_{2}\end{pmatrix}&space;\leq&space;\begin{pmatrix}&space;-2&space;\\&space;-1&space;\end{pmatrix}\\&space;&&space;y_{1},&space;y_{2}&space;\leq&space;0&space;\end{align*}" title="\begin{align*} \max_{y_{1},y_{2}} & \begin{pmatrix} 3 & 2\end{pmatrix}\begin{pmatrix} y_{1} \\ y_{2}\end{pmatrix} \\ \mathrm{s.t.} &\begin{pmatrix} 1 & 1 \\ 1 & 0 \end{pmatrix}\begin{pmatrix} y_{1} \\ y_{2}\end{pmatrix} \leq \begin{pmatrix} -2 \\ -1 \end{pmatrix}\\ & y_{1}, y_{2} \leq 0 \end{align*}" /></a>

The optimal solutions of the primal and dual is 

<a href="https://www.codecogs.com/eqnedit.php?latex=x_{1}&space;=&space;2,&space;x_{2}&space;=&space;1&space;\hspace{1&space;em}&space;y_{1}&space;=&space;-1,&space;y_{2}&space;=&space;-1" target="_blank"><img src="https://latex.codecogs.com/gif.latex?x_{1}&space;=&space;2,&space;x_{2}&space;=&space;1&space;\hspace{1&space;em}&space;y_{1}&space;=&space;-1,&space;y_{2}&space;=&space;-1" title="x_{1} = 2, x_{2} = 1 \hspace{1 em} y_{1} = -1, y_{2} = -1" /></a>

and with the Binv matrix equal to 
<a href="https://www.codecogs.com/eqnedit.php?latex=\mathrm{A^{-1}}&space;=&space;\begin{pmatrix}&space;0&space;&&space;1&space;\\&space;1&space;&&space;-1&space;\end{pmatrix}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\mathrm{A^{-1}}&space;=&space;\begin{pmatrix}&space;0&space;&&space;1&space;\\&space;1&space;&&space;-1&space;\end{pmatrix}" title="\mathrm{A^{-1}} = \begin{pmatrix} 0 & 1 \\ 1 & -1 \end{pmatrix}" /></a>

I am in general interested in the Binv matrix and want to find out the "composition" of the dual variables, i.e. parts of the sum in

<a href="https://www.codecogs.com/eqnedit.php?latex=y_{i}&space;=&space;\mathrm{A^{-T}}_{i,\cdot}c" target="_blank"><img src="https://latex.codecogs.com/gif.latex?y_{i}&space;=&space;\mathrm{A^{-T}}_{i,\cdot}c" title="y_{i} = \mathrm{A^{-T}}_{i,\cdot}c" /></a>

i.e. in this case, I would like to get 
<a href="https://www.codecogs.com/eqnedit.php?latex=y_{1}&space;=&space;0\cdot&space;(-2)&space;&plus;&space;1&space;\cdot&space;(-1)&space;=&space;0&space;-&space;1&space;\\&space;y_{2}&space;=&space;1\cdot&space;(-2)&space;&plus;&space;-1&space;\cdot&space;(-1)&space;=&space;-2&space;&plus;&space;1" target="_blank"><img src="https://latex.codecogs.com/gif.latex?y_{1}&space;=&space;0\cdot&space;(-2)&space;&plus;&space;1&space;\cdot&space;(-1)&space;=&space;0&space;-&space;1&space;\\&space;y_{2}&space;=&space;1\cdot&space;(-2)&space;&plus;&space;-1&space;\cdot&space;(-1)&space;=&space;-2&space;&plus;&space;1" title="y_{1} = 0\cdot (-2) + 1 \cdot (-1) = 0 - 1 \\ y_{2} = 1\cdot (-2) + -1 \cdot (-1) = -2 + 1" /></a>

When I use CyLp, I formulate the model as 

```
import numpy as np
from cylp.cy import CyClpSimplex

s = CyClpSimplex()

#Add variables
x1 = s.addVariable('x1', (1,1))
x2 = s.addVariable('x2', (1,1))

s += x1  >= 0
s += x2  >= 0
s += x1  <= 2
s += x1  + x2  <= 3

s.objective =  -2 * x1.sum() - x2.sum()
s.dual(startFinishOptions='x')
```

> Clp0006I 0  Obj 0 Dual inf 2.999998 (2)
> Clp0000I Optimal - objective value -5

The solution of such the primal program is correct, for the dual I have only the dual variable corresponding to the "composite" equation
```
print(s.primalVariableSolution)
print(s.dualConstraintSolution)
```
> {'x1': {(0, 0): 2.0}, 'x2': {(0, 0): 1.0}}
> {'R_46': array([-1.])}

Moreover, I do not understand much to what this value then represents (seems that A = (1))
```
print(s.basisInverse)
```
> [[1.]]

While I am getting just one constraint but potentially three!? variables in the basis space?
```
print(s.nConstraints)
print(s.nVariables)
print(s.basicVariables)
print(s.varIsBasic)
```
> 1
> 2
> [1]
> [False  True False]

Is there any way how to get this partial sum (which "costs" c influence the dual variable y_i) from the CyLp package? Or how to subset the c vector (s.objectiveCoefficients)  by basic variables (s.varIsBasic) so I can multiply by inverse of B of corresponding dual variable row (s.getBInvCol()) to get the dual variable value? I could imagine something like 
```
binv = np.empty(min(s.nConstraints, s.nVariables))
s.getBInvCol(0,binv)
print(binv)
binv*s.objectiveCoefficients[s.basicVariables]
```
to work but if fails as soon as there is a True value in s.varIsBasic in a field which is greater than number of variables in the program.. (we have 2 variables but s.varIsBasic has length 3..)

**Comment by tkralphs** [comment]
I didn't completely follow your explanation, but I think your confusion is because LP solvers always convert the problem to the standard form (equality constraints and all non-negative variables) internally. Wehn your inequality constraint is converted to standard form, a slack variable is introduced. The slack variables can also be basic (whenever the constraint is not tight) and the corresponding unit columns can be part of the basis matrix, so whenever you are querying anything related to the basis, you have to account for those additional variable and that the constraint matrix is not the one you started with. When querying the primal solution, these slack variables are filtered out. Does that help?

**Comment by xrust01** [comment]
Thank you for the comment, if the basis variables would correspond to slack variables, then I could easily filter them out too as their coefficients in the objective are 0.. which would help.

The only confusion now, when I change the constraint to
```s += x1  + x2  == 3```
the property 
```print(s.varIsBasic)```
still returns a list of three elements. But in this case, no slack variable should be introduced? Or does it ad slack variable even for equality constraints?

**Comment by tkralphs** [comment]
Sorry for the delay. Yes, even for equality constraints, we still add an artificial variable, basically so that there is always a starting feasible basis consisting of all slack variables. I'm going to close this issue for now, please feel free to re-open if needed.

**Comment by xrust01** [comment]
Thanks, its ok, this solved the issue (the fact that you add slack for equality constraints..) Then I could indentify the indices returned by the basis (and the fact that the total number always was num of variables plus num of constraints). Thanks a lot
