### ISSUE TITLE
Problem when I try to install on macOS

### ISSUE THREAD

**Issue by RobinTilman** [coin-or/CyLP#90]
Hello, I got this error message when I try to install cylp with pip3 on macOS 10.15.3 and python 3.7.6
I have set correctly PKG_CONFIG_PATH and COIN_INSTALL_DIR and I have installed cbc.
What can I do to install it properly ?  Thanks

  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/usr/local/Cellar/cbc/2.10.3_/include/coin-or -I./cylp/cpp -I./cylp/cy -I/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/include -I. -I/usr/local/Cellar/cbc/2.10.3_/include/coin -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c cylp/cpp/IClpPrimalColumnPivotBase.cpp -o build/temp.macosx-10.9-x86_64-3.7/cylp/cpp/IClpPrimalColumnPivotBase.o -w -std=c++11
    **In file included from cylp/cpp/IClpPrimalColumnPivotBase.cpp:1:
    ./cylp/cpp/IClpPrimalColumnPivotBase.h:5:10: fatal error: 'ClpPrimalColumnPivot.hpp' file not found
    #include "ClpPrimalColumnPivot.hpp"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    error: command 'gcc' failed with exit status 1**
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/qr/wlf5dn4j3qv10651zwtxcpcc0000gn/T/pip-install-n3qvvojt/cylp/setup.py'"'"'; __file__='"'"'/private/var/folders/qr/wlf5dn4j3qv10651zwtxcpcc0000gn/T/pip-install-n3qvvojt/cylp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/qr/wlf5dn4j3qv10651zwtxcpcc0000gn/T/pip-record-py5crv3s/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m/cylp Check the logs for full command output.

**Comment by tkralphs** [comment]
From the paths in the compile command, I guess that you have installed Cbc with homebrew. In that case, you should not set `COIN_INSTALL_DIR`---this is only for when you build and install the source yourself with coinbrew, and it assumes the directory structure is the way coinbrew would set it up, whereas homebrew sets things up much differently. I guess I could put in some logic to detect that some expected files are missing and give a more useful message indicating not to use COIN_INSTALL_DIR. 

You also should not need to set `PKG_CONFIG_PATH`, as the homebrew version of pkg-config already knows where to look, although I guess it probably doesn't hurt. 

Try re-running without any environment variables set and I guess it should work.

**Comment by tkralphs** [comment]
Umm, I see that the documentation is a bit misleading. I will fix that.

**Comment by RobinTilman** [comment]
Thank you for your quick response. Unfortunately this is the error I get when I try to simply install cylp without setting any variable:


     ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/qr/wlf5dn4j3qv10651zwtxcpcc0000gn/T/pip-install-vsj977gy/cylp/setup.py'"'"'; __file__='"'"'/private/var/folders/qr/wlf5dn4j3qv10651zwtxcpcc0000gn/T/pip-install-vsj977gy/cylp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/qr/wlf5dn4j3qv10651zwtxcpcc0000gn/T/pip-install-vsj977gy/cylp/pip-egg-info
         cwd: /private/var/folders/qr/wlf5dn4j3qv10651zwtxcpcc0000gn/T/pip-install-vsj977gy/cylp/
    Complete output (29 lines):
    Traceback (most recent call last):
      File "/private/var/folders/qr/wlf5dn4j3qv10651zwtxcpcc0000gn/T/pip-install-vsj977gy/cylp/setup.py", line 58, in get_libs
        flags = (check_output(['pkg-config', '--libs', 'cbc'])
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 411, in check_output
        **kwargs).stdout
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 488, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1551, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'pkg-config': 'pkg-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/qr/wlf5dn4j3qv10651zwtxcpcc0000gn/T/pip-install-vsj977gy/cylp/setup.py", line 115, in <module>
        libs, libDirs, incDirs = get_libs()
      File "/private/var/folders/qr/wlf5dn4j3qv10651zwtxcpcc0000gn/T/pip-install-vsj977gy/cylp/setup.py", line 94, in get_libs
        ''')
    Exception:
                Could not find location of COIN installation.
                Please ensure that either
                * COIN_INSTALL_DIR is set to the location of the installation,
                * PKG_CONFIG_PATH points to the location of the .pc files, or
                * The cbc executable is in your executable path and is installed
                at the same location as the libraries.
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.


Do you have any idea to fix this ?

**Comment by tkralphs** [comment]
You don't seem to have pkg-config installed. I thought this was required for homebrew to work, but maybe not. If you do
```
brew install pkg-config
```
everything should work. In the meantime you pushed me to completely overhaul the documentation and I hope it's a lot clearer now. I also updated the documentation at
https://coin-or.github.io/CyLP. Hope it helps!

**Comment by RobinTilman** [comment]
Thank you for your time, my problem is solved! Have a nice day

**Comment by tkralphs** [comment]
No problem, thanks for the report!
