### ISSUE TITLE
CyLP install error: Too few arguments to function void CbcMain0

### ISSUE THREAD

**Issue by dasguptap** [coin-or/CyLP#91]
I am getting an error while installing CyLP saying that there are mismatched arguments for calls to CbcMain0, CbcMain1 methods. The output with the errors is given below. I'd very much appreciate any help or suggestions to fix this problem.

Environment: ubuntu 16.04, python 3.5, Cbc 2.10.5

dasgupta@normandy:~/CyLP$ python3 setup.py install
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
/usr/local/lib/python3.5/dist-packages/setuptools/dist.py:388: UserWarning: Normalizing '0.9.4
' to '0.9.4'
  normalized_version,
running install
running build
running build_py
running build_ext
building 'cylp.cy.CyCbcModel' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/dasgupta/dist/include/coin-or -I/home/dasgupta/dist/include/coin-or/asl -I/home/dasgupta/dist/include/coin-or/glpk -I/home/dasgupta/dist/include/coin-or/mumps -I/home/dasgupta/dist/include/coin-or/metis -I./cylp/cpp -I./cylp/cy -I/usr/local/lib/python3.5/dist-packages/numpy/core/include -I. -I/home/dasgupta/dist/include/coin -I/usr/include/python3.5m -c cylp/cpp/ICbcModel.cpp -o build/temp.linux-x86_64-3.5/cylp/cpp/ICbcModel.o -w -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cylp/cpp/ICbcModel.cpp: In member function ‘int ICbcModel::cbcMain()’:
cylp/cpp/ICbcModel.cpp:34:23: error: too few arguments to function ‘void CbcMain0(CbcModel&, CbcSolverUsefulData&)’
         CbcMain0(*this);
                       ^
In file included from cylp/cpp/ICbcModel.cpp:4:0:
/home/dasgupta/dist/include/coin-or/CbcSolver.hpp:311:6: note: declared here
 void CbcMain0(CbcModel &babSolver, CbcSolverUsefulData &solverData);
      ^
cylp/cpp/ICbcModel.cpp:38:46: error: no matching function for call to ‘CbcMain1(int, const char* [3], ICbcModel&)’
         returnCode = CbcMain1 (3, argv, *this);
                                              ^
In file included from cylp/cpp/ICbcModel.cpp:4:0:
/home/dasgupta/dist/include/coin-or/CbcSolver.hpp:313:5: note: candidate: int CbcMain1(int, const char**, CbcModel&, int (*)(CbcModel*, int), CbcSolverUsefulData&)
 int CbcMain1(int argc, const char *argv[], CbcModel &babSolver, int(CbcModel *currentSolver, int whereFrom), CbcSolverUsefulData &solverData);
     ^
/home/dasgupta/dist/include/coin-or/CbcSolver.hpp:313:5: note:   candidate expects 5 arguments, 3 provided
In file included from cylp/cpp/ICbcModel.cpp:4:0:
/home/dasgupta/dist/include/coin-or/CbcSolver.hpp:315:5: note: candidate: int CbcMain1(int, const char**, CbcModel&, CbcSolverUsefulData&)
 int CbcMain1(int argc, const char *argv[], CbcModel &babSolver,
     ^
/home/dasgupta/dist/include/coin-or/CbcSolver.hpp:315:5: note:   candidate expects 4 arguments, 3 provided
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by tkralphs** [comment]
You are probably trying to link to the current master version, which has a slightly changed API. At the moment, you need to use stable/2.10. I added a warning about that to the README, but I was afraid some people would miss it. I'll close this issue for now, but feel free to open it up again if this doesn't fix the problem.

**Comment by dasguptap** [comment]
Thanks for the tip, Ted. I was able to install CyLP with the stable 2.10 release. Also, for some reason, I could not get the pip install to work, but cloning the git and using 'python setup.py install' worked. Best,

**Comment by tkralphs** [comment]
Thanks for the report, could be a file that's missing in the distribution, but is in the git repo. I thought I had gotten all those, though. I'll give it a try.
