### ISSUE TITLE
Set CBC MaximumSeconds

### ISSUE THREAD

**Issue by NOD507** [coin-or/CyLP#95]
Hi, is there a way to set a time limit for the CBC solver exectution from CyLP ?

I have been testing CyLP with a model that was taking  too much time to generate on python mip. CyLP is wayyy faster thanks to being able to use Array operations for constraints instead of nested loops for multidimensional arrays. Model generation went down from more than 10 minutes to 10 seconds!

 Im just missing a way to set the time limit for cbc. 

In python mip theres a way to set this and others parameters  as seen here https://python-mip.readthedocs.io/en/latest/quickstart.html#performance-tuning

Anyway this is fantastic, for now im just exporting the model. It would be great if theres a way to set the time limit.

Thanks for your help

**Comment by tkralphs** [comment]
Yes, just 
```
cbcModel.maximumSeconds = 600
cbcModel.solve()
```
See source here: https://github.com/coin-or/CyLP/blob/master/cylp/cy/CyCbcModel.pyx#L237. It's easy to add properties, so feel free to request if other properties are needed.

**Comment by NOD507** [comment]
Thanks! that works great!
